name: unit-backend-tests

on: pull_request

jobs:
  unit-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Go to Backend and Run tests
        run: cd backend && npm i && npm test